### ISSUE TITLE
Type 'RTCCameraVideoCapturer' has no member 'format' Swift 4.2

### ISSUE THREAD

**Issue by saroar** [kurzdigital/WAL#1]
http://prntscr.com/m6nm5f

from this code 

```
let format = RTCCameraVideoCapturer.format(
            for: device,
            constraints: config.formatConstraints)
```

file name `WebRTCConnection.swift`

error -> Type 'RTCCameraVideoCapturer' has no member 'format'
Swift Version 4.2 

how i can fixed it

**Comment by saroar** [comment]
not working or real device but work on simulator :(

**Comment by ChristianNorbertBraun** [comment]
Hi there,
I'm unable to reproduce your problem.
You could try to run `pod update` again. 
Please post the dependency versions from the Podfile.lock.

Could you check out our [Whale Demo Project](https://github.com/kurzdigital/Whale) and follow the instructions from the README.md to reproduce the error?

**Comment by saroar** [comment]
i think its webRTC problem not ur Demo Project

**Comment by ChristianNorbertBraun** [comment]
As I can't reproduce the problem and the Demo projects seems to be working I close this issue.
