### ISSUE TITLE
SpreedClient.swift#L117 how to implement own back end

### ISSUE THREAD

**Issue by saroar** [kurzdigital/WAL#2]
hi can you help me little bit find out this code 
https://github.com/kurzdigital/WAL/blob/master/WAL/Signaling/SpreedClient.swift#L117
for back end i am trying to handle in my back end with Swift language

**Comment by ChristianNorbertBraun** [comment]
This library is hard wired with the spreed signaling server. All the required resources are linked within the README.md. 
If you want to use an other signaling server feel free to fork this project and implement it by yourself.
The files you need to change are the [SpreedClient](https://github.com/kurzdigital/WAL/tree/master/WAL/Signaling), [WebRTCConnection](https://github.com/kurzdigital/WAL/blob/master/WAL/WebRTCConnection.swift) and the [SignalingMessages](https://github.com/kurzdigital/WAL/blob/master/WAL/Entities/SignalingMessage.swift).
